#!/usr/bin/env bash

# Run Model Matrix with Standalone Spark cluster

if [ -z ${SPARK_HOME} ]; then
    echo 'SPARK_HOME environment variable is not defined'
    exit 1
fi

if [ -z ${SPARK_MASTER} ]; then
    echo 'SPARK_MASTER environment variable is not defined'
    exit 1
fi

# Prepare Model Matrix cmd
$SPARK_HOME/bin/spark-submit \
--master $SPARK_MASTER \
--driver-java-options "-Dlog4j.configuration=file:./modelmatrix-cli/conf/log4j.properties -Dconfig.file=./modelmatrix-cli/conf/application.conf -Dspark.io.compression.codec=lzf" \
--class com.collective.modelmatrix.cli.ModelMatrixCli \
./modelmatrix-cli/target/scala-2.10/model-matrix-cli.jar ${1+"$@"}
