#!/usr/bin/env bash

# Run Model Matrix in Spark on Yarn mode

if [ -z ${SPARK_HOME} ]; then
    echo 'SPARK_HOME environment variable is not defined'
    exit 1
fi

# Prepare Model Matrix cmd
$SPARK_HOME/bin/spark-submit \
--master yarn-client \
--num-executors 5 \
--executor-memory 10g \
--executor-cores 6 \
--driver-memory 6g \
--driver-java-options "-Dlog4j.configuration=file:./modelmatrix-cli/conf/log4j.properties -Dconfig.file=./modelmatrix-cli/conf/application.conf" \
--class com.collective.modelmatrix.cli.ModelMatrixCli \
./modelmatrix-cli/target/scala-2.10/model-matrix-cli.jar ${1+"$@"}
